TicketChange/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TicketChange.Models;


namespace TicketChange.Controllers
{
    public class ForumController : Controller
    {

        private TicketChangeEntities db = new TicketChangeEntities();
        public DateTime CreateTime { get; set; }

        #region 文章列表 List
        public ActionResult ArticleList(int aid = 1)
        {
            // _ID變數，目前位於第幾頁？
            // PageSize變數，每一頁，要展示幾筆記錄？            
            int PageSize = 5;

            // RecordCount變數，符合條件的總共有幾筆記錄？
            int RecordCount = db.Article.Count();

            // NowPageCount，目前正在觀賞這一頁的紀錄
            int NowPageCount = 0;
            if (aid > 0)
            {
                NowPageCount = (aid - 1) * PageSize;    // PageSize，每頁展示5筆紀錄（上面設定過了）
            }
            var ListAll = (from art in db.Article
                           join us in db.User on art.ID equals us.ID
                           orderby art.ArtID // 若寫 descending ，則是反排序（由大到小）
                           select art).Skip(NowPageCount).Take(PageSize);    // .Skip() 從哪裡開始（忽略前面幾筆記錄）。 .Take()呈現幾筆記錄

            if (ListAll == null)
            {   // 找不到任何記錄
                return HttpNotFound();
            }
            else
            {

                #region    

                // Pages變數，「總共需要幾頁」才能把所有紀錄展示完畢？
                int Pages;
                if ((RecordCount % PageSize) > 0)
                {   //-- %，除法，傳回餘數
                    Pages = ((RecordCount / PageSize) + 1);   //-- ( / )除法。傳回整數。  如果無法整除，有餘數，則需要多出一頁來呈現。 
                }
                else
                {
                    Pages = (RecordCount / PageSize);   //-- ( /)除法。傳回整數
                }


                System.Text.StringBuilder sbPageList = new System.Text.StringBuilder();
                if (Pages > 0)
                {   //有傳來「頁數(p)」，而且頁數正確（大於零），出現<上一頁>、<下一頁>這些功能
                    sbPageList.Append("<div id='pageBtn' align='center'>");

                    if (aid > 1)
                    {   //======== 分頁功能（上一頁 / 下一頁）=========start===                
                        sbPageList.Append("<a href='?aid=" + (aid - 1) + "'><i class='fas fa-angle-left'></i></a>" + "&nbsp;&nbsp;&nbsp;");
                    }

                    int block_page = 0;
                    block_page = aid / 10;   //--只取除法的整數成果（商），若有餘數也不去管它。


                    for (int K = 0; K <= 10; K++)
                    {
                        if ((block_page * 10 + K) <= Pages)
                        {   //--- Pages 資料的總頁數。共需「幾頁」來呈現所有資料？
                            if (((block_page * 10) + K) == aid)
                            {   //--- id 就是「目前在第幾頁」
                                sbPageList.Append("<b>" + aid + "</b>" + "&nbsp;&nbsp;&nbsp;");
                            }
                            else
                            {
                                if (((block_page * 10) + K) != 0)
                                {
                                    sbPageList.Append("<a href='?aid=" + (block_page * 10 + K) + "'>" + (block_page * 10 + K) + "</a>");
                                    sbPageList.Append("&nbsp;&nbsp;&nbsp;");
                                }
                            }
                        }
                    }  //for迴圈 end

                    if (aid < Pages)
                    {
                        sbPageList.Append("<a href='?aid=" + (aid + 1) + "'><i class='fas fa-angle-right'></i></a>");
                    }

                }
                #endregion

                ViewBag.PageList = sbPageList.ToString();


                return View(ListAll.ToList());
            }


        }
        #endregion

        #region 最新排序
        public ActionResult NewestList(int aid = 1)
        {
            int PageSize = 5;

            // RecordCount變數，符合條件的總共有幾筆記錄？
            int RecordCount = db.Article.Count();

            // NowPageCount，目前正在觀賞這一頁的紀錄
            int NowPageCount = 0;
            if (aid > 0)
            {
                NowPageCount = (aid - 1) * PageSize;
            }

            var ListAll = (from art in db.Article
                           join us in db.User on art.ID equals us.ID
                           orderby art.ArtTime descending // 若寫 descending ，則是反排序（由大到小）
                           select art).Skip(NowPageCount).Take(PageSize);    // .Skip() 從哪裡開始（忽略前面幾筆記錄）。 .Take()呈現幾筆記錄

            if (ListAll == null)
            {   // 找不到任何記錄
                return HttpNotFound();
            }
            else
            {

                #region    // 畫面下方的「分頁列」。「每十頁」一間隔，分頁功能

                // Pages變數，「總共需要幾頁」才能把所有紀錄展示完畢？
                int Pages;
                if ((RecordCount % PageSize) > 0)
                {   //-- %，除法，傳回餘數
                    Pages = ((RecordCount / PageSize) + 1);   //-- ( / )除法。傳回整數。  如果無法整除，有餘數，則需要多出一頁來呈現。 
                }
                else
                {
                    Pages = (RecordCount / PageSize);   //-- ( /)除法。傳回整數
                }



                System.Text.StringBuilder sbPageList = new System.Text.StringBuilder();
                if (Pages > 0)
                {
                    sbPageList.Append("<div id='pageBtn' align='center'>");

                    if (aid > 1)
                    {
                        sbPageList.Append("<a href='?aid=" + (aid - 1) + "'><i class='fas fa-angle-left'></i></a>" + "&nbsp;&nbsp;&nbsp;");
                    }

                    int block_page = 0;
                    block_page = aid / 10;


                    for (int K = 0; K <= 10; K++)
                    {
                        if ((block_page * 10 + K) <= Pages)
                        {   //--- Pages 資料的總頁數。共需「幾頁」來呈現所有資料？
                            if (((block_page * 10) + K) == aid)
                            {   //--- id 就是「目前在第幾頁」
                                sbPageList.Append("<b>" + aid + "</b>" + "&nbsp;&nbsp;&nbsp;");
                            }
                            else
                            {
                                if (((block_page * 10) + K) != 0)
                                {
                                    sbPageList.Append("<a href='?aid=" + (block_page * 10 + K) + "'>" + (block_page * 10 + K) + "</a>");
                                    sbPageList.Append("&nbsp;&nbsp;&nbsp;");
                                }
                            }
                        }
                    }  //for迴圈 end

                    if (aid < Pages)
                    {
                        sbPageList.Append("<a href='?aid=" + (aid + 1) + "'><i class='fas fa-angle-right'></i></a>");
                    }

                }

                #endregion

                ViewBag.PageList = sbPageList.ToString();

                return View("ArticleList", ListAll.ToList());
            }



        }

        #endregion

        #region 文章分類

        public ActionResult ArticleCategoery(int? cat)
        {
            List<Article> articles = (from i in db.Article
                                      join us in db.User on i.ID equals us.ID
                                      orderby i.ArtID
                                      where i.ArtCategory == cat
                                      select i).ToList();

            return View("ArticleList", articles);

        }

        #endregion

        #region 文章搜尋

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ArticleList(Article art)
        {
            string aTitle = art.ArtTitle;
            ViewData["sw"] = aTitle;

            var ListAll = db.Article.Select(x => x);
            if (!string.IsNullOrWhiteSpace(aTitle))
            {
                ListAll = ListAll.Where(x => x.ArtTitle.Contains(aTitle));
            }

            //if ((art != null) && (ModelState.IsValid))
            //{
            //    return View("ArticleList", ListAll.ToList());
            //}
            //else
            //{
            //    return HttpNotFound();
            //}

            if ((art != null) && (ModelState.IsValid))
            {
                return View("ArticleList", ListAll.ToList());
            }
            else
            {
                return HttpNotFound();
            }

        }
        #endregion

        #region 新增文章 Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(ForDetial article)
        {

            if ((article != null) && (ModelState.IsValid))
            {

                // add article
                article.ArtTime = DateTime.Now;
                Article newArt = article.GetArticle();
                db.Article.Add(newArt);
                db.SaveChanges();

                //using (var context = new ForumEntities())
                //{
                //    context.Article.Add(article);
                //    context.SaveChanges();
                //    int id = article.ArtID; // Yes it's here
                //}

                // 撈出文章id(在迴圈外面撈)
                int artID = newArt.ArtID;

                // get input tag's array 
                string[] tag = article.Tag.Split(',');

                bool check = false;  // check tag 是否存在的flag
                int tagID = 0;
                for (int i = 0; i < tag.Length; i++)
                {
                    var temp = tag[i];
                    //check tagName是否存在
                    check = CheckTagName(tag[i]);
                    // 不存在則新增，存在則跳過
                    if (!check)
                    {
                        
                        Tag modelTag = new Tag();
                        modelTag.TagContent = temp;
                        db.Tag.Add(modelTag);
                        db.SaveChanges();

TicketChange/Views/Shared/_Account.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/AccountStyle.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.4.1.js"></script>
</head>

@{var callback = new { callback = Request.Url.ToString() };/*紀錄當前URL*/}
<body>
    <div id="accountnav">
        @if (Session["AccountData"] == null)
        {
            <div type="button" class="dropdown-toggle chip">
                登入
            </div>
            <div class="menu-down my-menu">
                <a href="@Url.Action("GoogleLoginDirect", "Login" , callback)" class="dropdown-item my-list">
                    <img src="~/img/LoginLogo/google.png" width="40" alt="Google Login" />
                </a>
                <a href="@Url.Action("FBLoginDirect","Login",callback)" class="dropdown-item  my-list">
                    <img src="~/img/LoginLogo/facebook.png" width="40" alt="FB Login" />
                </a>
                <a href="@Url.Action("LineLoginDirect","Login",callback)" class="dropdown-item  my-list">
                    <img src="~/img/LoginLogo/line.png" width="40" alt="Line Login" />
                </a>
            </div>
        }
        else
        {
            <!--RWD-->
            <script>
        $(window).ready(checksize);
        $(window).resize(checksize);
        function checksize() {
            if ($(window).width() < parseInt($("#username").css("width"))*4 + 500) {
                $("#username").css("display", "none");
                if ($("#nameinmenu").length ==0) {
                    $("#usermenu").prepend("<span id='nameinmenu' class='dropdown-item my-list ' sytle='disabled: disabled'>@GetUser.name()</span>")
                }
            } else {
                $("#username").css("display", "inline");
                $("#nameinmenu").remove();
            }
        }
            </script>
            <div type="button" class="chip ">
                <nobr style="width:30px">
                    <img src="@Url.Content(GetUser.loginMode())" alt="login_mode" width="30" height="30">
                    <nobr></nobr>
                </nobr>
                <nobr>
                    <img src=@GetUser.pictureUrl() alt="Person" width="30" height="30">
                </nobr>
                <nobr id="username">@GetUser.name()</nobr>
            </div>
            <div id="usermenu" class="menu-down my-menu">
                <a class="dropdown-item my-list" href="@Url.Action("MyArticle", "Login" )">我的文章</a>
                <a class="dropdown-item my-list" sytle="disabled:disabled">我的通知 <nobr class="my-notice"></nobr></a>
                @*<button class="dropdown-item my-list" id="okbody1">通知設定</button>
                    <div type="button" class="dropdown-item my-list" data-toggle="modal" data-target="#exampleModalLong">帳戶</div>*@
                <a class="dropdown-item my-list" href="@Url.Action("Logout", "Login" ,callback)">登出</a>
            </div>
            //取得通知
            <script>
                $.getJSON("@Url.Action("GetNotice", "Login")",(notice) => {
                    console.log(notice);
                    if (notice.length > 0) {
                        $(".my-notice").html(`未讀${notice.length}`);
                        $(".chip :nth-child(2)").html(`${notice.length}`);
                    } else {
                        $(".chip :nth-child(2)").css = "";
                    }
        })
            </script>
        }
        <!--$.getJSON("/Home/Image", `title=${info.event.title}`, function (thedata) {});-->
    </div>

    <!-- Modal -->
    <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    ...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

TicketChange/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="~/img/tickettok_icon.png" type="image/x-icon" />
    <title>@ViewBag.Title - @ViewBag.websiteName</title>
    <link rel="stylesheet" href="~/Content/bootstrap.css">

    <link rel="stylesheet" href="~/Content/maicons.css">

    <link rel="stylesheet" href="~/Scripts/vendor/animate/animate.css">

    <link rel="stylesheet" href="~/Scripts/vendor/owl-carousel/css/owl.carousel.css">

    <link rel="stylesheet" href="~/Scripts/vendor/fancybox/css/jquery.fancybox.css">

    <link rel="stylesheet" href="~/Content/theme.css">

    @RenderSection("css", required: false)
</head>
<body>
    <!-- Back to top button -->
    <div class="back-to-top"></div>

    <header>
        <div style="height:70px" id="填充header" />
        <div class="fixed-top">
            <nav class="navbar navbar-expand-lg navbar-light bg-light" style="width: 80%;position: absolute;">
                <div class="container">
                    <img src="~/img/tickettok_icon.png" width="50" height="50" />
                    <a href="@Url.Action("index", "Home")" class="navbar-brand">Ticket<span class="text-primary">Tok!</span></a>

                    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse" id="navbarContent">
                        <ul class="navbar-nav ml-auto pt-3 pt-lg-0">
                            <li>
                                <form class="form-inline" action="/Home/Concert">
                                    <input name="searchString" class="form-control mr-sm-3" type="search" placeholder="請輸入搜尋..." aria-label="Search">
                                    <button class="btn btn-outline-warning my-2 my-sm-1" type="submit">查詢</button>
                                </form>
                            </li>
                            <li class="nav-item active">
                                <a href="@Url.Action("index", "Home")" class="nav-link">首頁</a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("About_Test", "Home")" class="nav-link">關於我們</a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Concert", "Home")" class="nav-link">演唱會</a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("ArticleList", "Forum")" class="nav-link">討論版</a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Calendar", "Home")" class="nav-link">行事曆</a>
                            </li>
                        </ul>
                    </div>
                </div><!-- .container -->
            </nav> <!-- .navbar -->
            @RenderPage("_Account.cshtml")
        </div>
    </header>

    @RenderBody()

  
    <footer class="page-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 py-3">
                    <h3>Ticket<span class="fg-primary">Tok!</span></h3>
                </div>
                <div class="col-lg-3 py-3">
                    <h5>聯絡資訊</h5>
                    <p>台中市公益路二段51號18樓</p>
                    <p>Email: example@mail.com</p>
                    <p>Phone: 0912-345-678</p>
                </div>

                <div class="col-lg-3 py-3">
                    <h5>認識TicketTok!</h5>
                    <ul class="footer-menu">
                        <li><a href="#">常見問題</a></li>
                        <li><a href="#">隱私權政策</a></li>
                        <li><a href="#">服務條款</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 py-3">
                    <h5>訂閱電子報</h5>
                    <form action="#">
                        <input type="text" class="form-control" placeholder="請輸入你的email">
                        <button type="submit" class="btn btn-primary btn-sm mt-2">提交</button>
                    </form>
                </div>
            </div>

            <hr>

            <div class="row mt-4">
                <div class="col-md-6">
                    <p>Copyright 2020. This template designed by <a href="https://macodeid.com">MACode ID</a></p>
                </div>
                <div class="col-md-6 text-right">
                    <div class="sosmed-button">
                        <a href="#"><span class="mai-logo-facebook-f"></span></a>
                        <a href="#"><span class="mai-logo-twitter"></span></a>
                        <a href="#"><span class="mai-logo-youtube"></span></a>
                        <a href="#"><span class="mai-logo-linkedin"></span></a>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/Scripts/js/jquery-3.5.1.min.js"></script>

    <script src="~/Scripts/js/bootstrap.bundle.min.js"></script>

    <script src="~/Scripts/vendor/owl-carousel/js/owl.carousel.min.js"></script>

    <script src="~/Scripts/vendor/wow/wow.min.js"></script>

    <script src="~/Scripts/vendor/fancybox/js/jquery.fancybox.min.js"></script>

    <script src="~/Scripts/vendor/isotope/isotope.pkgd.min.js"></script>

    <script src="~/Scripts/js/google-maps.js"></script>

    <script src="~/Scripts/js/theme.js"></script>

    @RenderSection("scripts", required: false)

    <script>
        $("#searchText").on("click", function () {
            $("#searchText").val("");
            $("#searchText").prop("style", "color:black");
        })
        $("#searchText").on("focusout", function () {
            $("#searchText").val("請輸入搜尋...");
        })
        $("#searchText").on("click", function () {
            console.log($("#test").width());
            console.log($("#test").height());
        })
    </script>


</body>